"""init

Revision ID: d37e995fdd51
Revises: 
Create Date: 2025-10-22 19:46:04.247648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37e995fdd51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_items_id_factura'), 'factura_items', ['id_factura'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_factura', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('nit', sa.String(), nullable=True),
    sa.Column('pago_metodo', sa.String(), nullable=True),
    sa.Column('entrega_metodo', sa.String(), nullable=True),
    sa.Column('envio_nombre', sa.String(), nullable=True),
    sa.Column('envio_telefono', sa.String(), nullable=True),
    sa.Column('envio_direccion', sa.String(), nullable=True),
    sa.Column('origen', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_numero_factura'), 'facturas', ['numero_factura'], unique=True)
    op.create_table('logistica_zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zona_nombre', sa.String(), nullable=False),
    sa.Column('tarifa_gtq', sa.Float(), nullable=False),
    sa.Column('tiempo_estimado_dias', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zona_nombre')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('tipo', sa.Enum('LIBRO', 'UTIL', name='tipo_producto_enum', native_enum=False), nullable=False),
    sa.Column('autor', sa.String(), nullable=True),
    sa.Column('editorial', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('paginas', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('token_verificacion', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('logistica_zonas')
    op.drop_index(op.f('ix_facturas_numero_factura'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_factura_items_id_factura'), table_name='factura_items')
    op.drop_table('factura_items')
    # ### end Alembic commands ###
